// Contract ABIs for PredictionMarket (Polymarket-style LMSR) and OptimisticOracle

export const PREDICTION_MARKET_ABI = [
    "constructor()",
    "error AlreadyInitialized()",
    "error NotInitialized()",
    "error NotAdmin()",
    "error InvalidFundAmount()",
    "error MarketNotPreparing()",
    "error MarketNotActive()",
    "error MarketNotFinished()",
    "error MarketAlreadyExists()",
    "error MarketNotFound()",
    "error TransferFailed()",
    "error InsufficientTokens()",
    "error AlreadyClaimed()",
    "error NoWinnings()",
    "error ResolutionTooEarly()",
    "error NoLPShares()",
    "event GlobalInitialized(address indexed admin, address indexed feeAuthority, uint256 creatorFeeAmount, uint256 bettingFeePercentage, uint256 fundFeePercentage)",
    "event MarketCreated(string indexed marketId, address indexed creator, uint256 liquidityGoal, int64 resolutionDate, string question)",
    "event MarketStatusUpdated(string indexed marketId, uint8 marketStatus)",
    "event LiquidityAdded(string indexed marketId, address indexed user, uint256 amount, uint256 shares)",
    "event LiquidityRemoved(string indexed marketId, address indexed user, uint256 shares)",
    "event TokensBought(string indexed marketId, address indexed user, bool isYes, uint256 amount, uint256 cost, uint256 fee)",
    "event TokensSold(string indexed marketId, address indexed user, bool isYes, uint256 amount, uint256 refund, uint256 fee)",
    "event WinningsClaimed(string indexed marketId, address indexed user, uint256 payout)",
    "event LPRewardsClaimed(string indexed marketId, address indexed user, uint256 reward)",
    "event MarketResolved(string indexed marketId, bool result)",
    "event Withdrawal(string indexed marketId, address indexed receiver, uint256 amount)",
    "function initialize(address _feeAuthority, uint256 _creatorFeeAmount, uint256 _bettingFeePercentage, uint256 _fundFeePercentage)",
    "function createMarket(string _marketId, string _question, int64 _resolutionDate, uint256 _liquidityGoal) payable",
    "function addLiquidity(string _marketId) payable",
    "function removeLiquidity(string _marketId)",
    "function claimLPRewards(string _marketId)",
    "function buyTokens(string _marketId, bool _isYes, uint256 _amount) payable",
    "function sellTokens(string _marketId, bool _isYes, uint256 _amount)",
    "function claimWinnings(string _marketId)",
    "function resolveMarket(string _marketId, bool _result)",
    "function requestOracleResolution(string _marketId)",
    "function finalizeFromOracle(string _marketId)",
    "function withdraw(string _marketId, address _receiver, uint256 _amount)",
    "function getMarket(string _marketId) view returns (tuple(address creator, uint8 marketStatus, bool result, uint256 qYes, uint256 qNo, uint256 b, uint256 totalVolume, uint256 liquidity, uint256 liquidityGoal, uint256 totalLPShares, uint256 accumulatedFees, int64 resolutionDate, string question, bytes32 oracleRequestId))",
    "function getGlobal() view returns (tuple(address admin, address feeAuthority, uint256 creatorFeeAmount, uint256 bettingFeePercentage, uint256 fundFeePercentage))",
    "function initialized() view returns (bool)",
    "function marketExists(string _marketId) view returns (bool)",
    "function getPrices(string _marketId) view returns (uint256 yesPrice, uint256 noPrice)",
    "function estimateBuyCost(string _marketId, bool _isYes, uint256 _amount) view returns (uint256 cost, uint256 fee)",
    "function estimateSellRefund(string _marketId, bool _isYes, uint256 _amount) view returns (uint256 refund, uint256 fee)",
    "function getUserTokens(string _marketId, address _user) view returns (uint256 yesTokens, uint256 noTokens)",
    "function getLPInfo(string _marketId, address _user) view returns (uint256 shares, uint256 totalShares, bool claimed)",
    "function updateFeeAuthority(address _new)",
    "function updateFees(uint256 _betting, uint256 _fund)",
    "function transferAdmin(address _new)"
];

export const OPTIMISTIC_ORACLE_ABI = [
    "constructor()",
    "error AlreadyDisputed()",
    "error AlreadySettled()",
    "error DisputeWindowActive()",
    "error DisputeWindowExpired()",
    "error InsufficientBond()",
    "error InvalidValue()",
    "error NotAdmin()",
    "error NotDisputed()",
    "error ProposalAlreadyExists()",
    "error ProposalNotFound()",
    "error RequestAlreadyResolved()",
    "error RequestNotFound()",
    "error ResolutionTimeNotReached()",
    "error TransferFailed()",
    "event AnswerDisputed(bytes32 indexed questionId, address indexed disputer, uint256 bondAmount)",
    "event AnswerProposed(bytes32 indexed questionId, address indexed proposer, int256 proposedValue, uint256 bondAmount, uint256 disputeDeadline)",
    "event AnswerSettled(bytes32 indexed questionId, int256 finalValue, address winner, uint256 reward)",
    "event OracleRequestCreated(bytes32 indexed questionId, address indexed requester, string question, uint256 resolutionTime)",
    "function admin() view returns (address)",
    "function adminBond() view returns (uint256)",
    "function canDispute(bytes32 _questionId) view returns (bool)",
    "function canSettle(bytes32 _questionId) view returns (bool)",
    "function disputeAnswer(bytes32 _questionId) payable",
    "function disputeTimeRemaining(bytes32 _questionId) view returns (uint256)",
    "function disputeWindow() view returns (uint256)",
    "function getProposal(bytes32 _questionId) view returns (tuple(address proposer, int256 proposedValue, uint256 proposalTime, uint256 bondAmount, bool disputed, address disputer, uint256 disputeBond, bool settled))",
    "function getRequest(bytes32 _questionId) view returns (tuple(address requester, bytes32 questionId, string question, uint256 requestTime, uint256 resolutionTime, bool resolved, int256 resolvedValue))",
    "function getRequiredBond(address _caller) view returns (uint256)",
    "function getResolvedValue(bytes32 _questionId) view returns (int256)",
    "function isResolved(bytes32 _questionId) view returns (bool)",
    "function proposeAnswer(bytes32 _questionId, int256 _value) payable",
    "function requestResolution(string _question, uint256 _resolutionTime) returns (bytes32 questionId)",
    "function resolveDispute(bytes32 _questionId, int256 _finalValue)",
    "function setAdminBond(uint256 _newBond)",
    "function setDisputeWindow(uint256 _newWindow)",
    "function setUserBond(uint256 _newBond)",
    "function settleProposal(bytes32 _questionId)",
    "function transferAdmin(address _newAdmin)",
    "function userBond() view returns (uint256)"
];


export const MULTI_OUTCOME_ORACLE_ABI = [
    "constructor()",
    "function admin() view returns (address)",
    "function adminBond() view returns (uint256)",
    "function canDispute(bytes32 _questionId) view returns (bool)",
    "function canSettle(bytes32 _questionId) view returns (bool)",
    "function disputeAnswer(bytes32 _questionId) payable",
    "function disputeTimeRemaining(bytes32 _questionId) view returns (uint256)",
    "function disputeWindow() view returns (uint256)",
    "function getProposal(bytes32 _questionId) view returns (tuple(address proposer, int256 proposedValue, uint256 proposalTime, uint256 bondAmount, bool disputed, address disputer, uint256 disputeBond, bool settled))",
    "function getRequest(bytes32 _questionId) view returns (tuple(address requester, bytes32 questionId, string question, uint256 requestTime, uint256 resolutionTime, bool resolved, int256 resolvedValue, uint256 outcomeCount))",
    "function getRequiredBond(address _caller) view returns (uint256)",
    "function getResolvedValue(bytes32 _questionId) view returns (int256)",
    "function isResolved(bytes32 _questionId) view returns (bool)",
    "function proposeAnswer(bytes32 _questionId, int256 _value) payable",
    "function requestResolution(string _question, uint256 _resolutionTime, uint256 _outcomeCount) returns (bytes32 questionId)",
    "function resolveDispute(bytes32 _questionId, int256 _finalValue)",
    "function setAdminBond(uint256 _newBond)",
    "function setDisputeWindow(uint256 _newWindow)",
    "function setUserBond(uint256 _newBond)",
    "function settleProposal(bytes32 _questionId)",
    "function transferAdmin(address _newAdmin)",
    "function userBond() view returns (uint256)"
];

export const MULTI_OUTCOME_EVENT_ABI = [
    "function initialize(address _feeAuthority, uint256 _creatorFeeAmount, uint256 _bettingFeePercentage, uint256 _fundFeePercentage)",
    "function createEvent(string _eventId, string _question, string[] _outcomeNames, int64 _resolutionDate, uint256 _liquidityGoal) payable",
    "function fundEvent(string _eventId) payable",
    "function removeLiquidity(string _eventId)",
    "function claimLPRewards(string _eventId)",
    "function buyTokens(string _eventId, uint256 _outcomeIndex, bool _isYes, uint256 _amount) payable",
    "function sellTokens(string _eventId, uint256 _outcomeIndex, bool _isYes, uint256 _amount)",
    "function claimWinnings(string _eventId)",
    "function resolveEvent(string _eventId, int256 _winningOutcome)",
    "function setOracle(address _oracle)",
    "function requestOracleResolution(string _eventId)",
    "function finalizeFromOracle(string _eventId)",
    "function getEvent(string _eventId) view returns (tuple(address creator, uint8 status, string question, int64 resolutionDate, uint256 outcomeCount, uint256 liquidity, uint256 liquidityGoal, uint256 totalLPShares, int256 winningOutcome, bytes32 oracleRequestId))",
    "function getOutcome(string _eventId, uint256 _index) view returns (tuple(string name, uint256 qYes, uint256 qNo, uint256 b, uint256 totalVolume, uint256 accumulatedFees))",
    "function getOutcomePrices(string _eventId, uint256 _index) view returns (uint256 yesPrice, uint256 noPrice)",
    "function eventExists(string _eventId) view returns (bool)",
    "function getEventCount() view returns (uint256)",
    "function getGlobal() view returns (tuple(address admin, address feeAuthority, uint256 creatorFeeAmount, uint256 bettingFeePercentage, uint256 fundFeePercentage))",
    "function getUserTokens(string _eventId, uint256 _outcomeIndex, address _user) view returns (uint256 yesTokens, uint256 noTokens)",
    "function getLPInfo(string _eventId, address _user) view returns (uint256 shares, uint256 totalShares, bool claimed)",
    "function estimateBuyCost(string _eventId, uint256 _outcomeIndex, bool _isYes, uint256 _amount) view returns (uint256 cost, uint256 fee)"
];
