import React, { useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";

interface AboutSectionProps {
  selectedIndex: number;
}

const aboutAnswers = [
  {
    title: "What is Foresight?",
    content: [
      "Foresight is a decentralized prediction market platform built on Hedera. Users can forecast outcomes on real-world events — crypto prices, sports, politics, entertainment, and more — and earn rewards for accurate predictions.",
      "Unlike centralized betting platforms, Foresight is community-driven. Anyone can propose a new market, provide liquidity, and trade outcome tokens. All trades settle on-chain through smart contracts, ensuring full transparency and trustless execution.",
    ],
  },
  {
    title: "How do prediction markets work?",
    content: [
      "Each market on Foresight has two sides: Yes and No. When you buy Yes tokens, you're betting the event will happen. When you buy No tokens, you're betting it won't. Token prices move between 0 and 1 HBAR based on market demand using an LMSR (Logarithmic Market Scoring Rule) pricing model.",
      "When the event resolves, winning tokens are worth 1 HBAR each and losing tokens are worth 0. You can also sell your tokens at any time before resolution at the current market price. All pricing, settlement, and payouts are handled automatically by the smart contract.",
    ],
  },
  {
    title: "Is Foresight safe and secure?",
    content: [
      "Foresight runs entirely on Hedera smart contracts. Your funds are never held by a centralized party — they're managed by auditable on-chain logic. Every trade, liquidity deposit, and resolution is recorded on the Hedera ledger.",
      "Market resolution uses an Optimistic Oracle system: a proposed answer goes through a dispute window before being finalized. This ensures outcomes are accurate and community-verified. If a dispute arises, an admin can step in to resolve it fairly.",
    ],
  },
  {
    title: "How do I get started?",
    content: [
      "Connect a MetaMask wallet configured for the Hedera network. Once connected, you can browse active markets, buy Yes or No tokens, and track your positions from your profile page.",
      "If you want to create a market, head to the Propose page. Choose a data source (CoinGecko or DexScreener for crypto, or custom for other events), set a resolution date and liquidity goal, and submit. Once the funding goal is met, the market goes live automatically.",
    ],
  },
  {
    title: "What can I trade on Foresight?",
    content: [
      "Foresight supports markets across multiple categories: Crypto price predictions, Sports outcomes, News and politics, and Trending topics. New markets are created by the community, so the range of topics is always expanding.",
      "For crypto markets, Foresight integrates with CoinGecko and DexScreener APIs to pull real token data. You can create markets around whether a token will hit a certain price by a specific date, with automatic resolution powered by price feeds.",
    ],
  },
  {
    title: "How does liquidity work?",
    content: [
      "Every market on Foresight needs liquidity to function. Liquidity providers (LPs) deposit HBAR into a market's pool during the funding phase. Once the liquidity goal is reached, the market activates and trading begins.",
      "LPs earn a share of the trading fees generated by the market, proportional to their contribution. After the market resolves, LPs can claim their share of the remaining pool plus accumulated fees. You can track your LP positions and fee earnings from the Funded Market tab on your profile.",
    ],
  },
  {
    title: "What are the fees?",
    content: [
      "Foresight charges a small creator fee when proposing a new market, a percentage-based fee on each trade (collected for liquidity providers), and a small fee on liquidity deposits. All fees are transparently defined in the smart contract and visible before you transact.",
      "Trading fees go directly to liquidity providers as a reward for supplying market depth. This creates a healthy incentive loop: more liquidity means tighter prices, which attracts more traders, which generates more fees for LPs.",
    ],
  },
];

const AboutSection: React.FC<AboutSectionProps> = ({ selectedIndex }) => {
  const section = aboutAnswers[selectedIndex];
  const answerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (answerRef.current && window.innerWidth < 768) {
      answerRef.current.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  }, [selectedIndex]);

  return (
    <div className="flex-1 py-4 md:py-6 flex flex-col gap-6 w-full max-w-3xl">
      <AnimatePresence mode="wait">
        <motion.div
          key={selectedIndex}
          ref={answerRef}
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -16 }}
          transition={{ duration: 0.25, ease: "easeOut" }}
          className="flex flex-col gap-5"
        >
          <h1 className="text-white text-2xl md:text-4xl font-semibold font-rubik leading-tight">
            {section.title}
          </h1>
          <div className="flex flex-col gap-4">
            {section.content.map((paragraph, idx) => (
              <motion.p
                key={idx}
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3, delay: 0.1 * idx, ease: "easeOut" }}
                className="text-[#9a9a9a] text-base md:text-lg font-normal font-satoshi leading-relaxed bg-[#1a1a1a] rounded-xl p-5 md:p-6 border border-[#232323]"
              >
                {paragraph}
              </motion.p>
            ))}
          </div>
        </motion.div>
      </AnimatePresence>
    </div>
  );
};

export { AboutSection };
